platform :ios, '7.0'

pod 'QMBTabs'
pod 'CocoaLumberjack'
pod 'RATreeView'
pod 'FontAwesomeTools'
pod 'AFNetworking', '~> 2.0'
pod 'XMLDictionary'
pod 'SSZipArchive'
pod 'WYPopoverController'
pod 'MPColorTools', '~> 1.4.1'
pod 'zipzap'
pod 'JVFloatLabeledTextField'
pod 'BButton',  :git => 'https://github.com/jessesquires/BButton.git'
pod 'GZIP'
pod 'FMDB'
pod 'Dropbox-iOS-SDK'
pod 'RFQuiltLayout'
pod 'NHAlignmentFlowLayout'
pod 'NHBalancedFlowLayout'
pod 'DMDynamicWaterfall'
pod 'BMFloatingHeaderCollectionViewLayout'
pod 'MYNStickyFlowLayout'
pod 'ARCollectionViewMasonryLayout'
pod 'CocoaHTTPServer'